version: 2.1

orbs:
  node: circleci/node@4.7.0
  aws-cli: circleci/aws-cli@2.0
  eb: circleci/aws-elastic-beanstalk@2.0.1

executors:
  docker-cimg:
    docker:
      - image: "cimg/base:stable"
jobs:
  build:
    executor: docker-cimg
    steps:
      - node/install
      - checkout
      - run:
          name: check envs
          command: |
            printenv
      - run:
          name: generate .env
          command: |
            printenv > ./udagram-api/.env
            cat ./udagram-api/.env
      - run:
          name: swap node versions
          command: |
            set +e
            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install v12
            nvm alias default 12.22.7

            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: install backend dependencies
          command: |
            npm run backend:install
      - run:
          name: install frontend dependencies
          command: |
            npm run frontend:install
      - run:
          name: build server
          command: |
            npm run backend:build
      - run:
          name: build frontend
          command: |
            npm run frontend:build
      - run:
          name: check .env
          command: |
            cat ./udagram-api/www/.env
      - persist_to_workspace:
          root: ./
          paths:
            - ./udagram-api
            - ./udagram-frontend
  deploy:
    executor: docker-cimg
    steps:
      - aws-cli/setup
      - eb/setup
      - node/install
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: check .env
          command: |
            cat ./udagram-api/www/.env
      - run:
          name: deploy udagram api
          command: |
            eb init udagram-backend -p node.js -r $AWS_DEFAULT_REGION 
            eb use Udagrambackend-env
            eb deploy -l version-<<pipeline.number>>
          working_directory: ./udagram-api
      - run:
          name: deploy udagram frontend
          command: |
            npm run frontend:deploy
      
workflows:
  udagram:
    jobs:
      - build
      - deploy:
          requires:
            - build
